### ISSUE TITLE
what's the unit of the output ?

### ISSUE THREAD

**Issue by 0xMadao** [sonots/fluent-plugin-latency#1]
hi,I confused about the unit of the output number by the `fluent-plugin-latency` plugin. as you mentioned in the `README`, the plugin is calculated the timestamp, so the unit is `s`?  
```
latency: {"max":47.327404499054,"avg":36.327404499054,"num":8}
``` 
for example, the output above means the `max` latency is `47.327404499054 s` and `avg` is `36.327404499054 s` in `8` total messages, am I  right?

**Comment by sonots** [comment]
you are right
